apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-k8s-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-k8s-demo
  template:
    metadata:
      labels:
        app: python-k8s-demo
    spec:
      containers:
      - name: python-k8s-demo
        image: mgelvoleo/python-k8s-demo:latest
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 20
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 40

