apiVersion: v1
kind: Service
metadata:
  name: python-k8s-service
spec:
  type: LoadBalancer
  selector:
    app: python-k8s-demo
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 30090

